name: Makefile CI

on:
  push:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v4

      - name: setup
        run: |
          git clone https://github.com/vitasdk/vdpm
          cd vdpm
          export VITASDK=/usr/local/vitasdk
          export PATH=$VITASDK/bin:$PATH
          ./bootstrap-vitasdk.sh
          ./install-all.sh

      - name: Build
        run:
          make

      - uses: actions/upload-artifact@v4
        with:
          name: out
          path: /
